### ISSUE TITLE
Duplicated records pending of review on save changes

### ISSUE THREAD

**Issue by jocor87** [edwardspec/mediawiki-moderation#32] opened 2018-03-12 23:40 UTC
When a user save your changes, review is added to Moderation Page, but is showing duplicated the records.

It only ocurr when user save your changes before publish.

![captura](https://user-images.githubusercontent.com/14800036/37314887-3afa5350-261c-11e8-812a-a94b6a5051f3.JPG)

Mediawiki 1.27 Moderation Extension: 1.1.0

**Comment by edwardspec** [comment] 2018-03-13 05:37
1) Are those edits of anonymous user? (i.e. IP address, not registered account)
2) Please clarify what "save your changes before publish" means.
3) Does the problem go away if you set $wgSessionCacheType=CACHE_DB; in LocalSettings.php?

**Comment by jocor87** [comment] 2018-03-13 20:50
**1. Are those edits of anonymous user? (i.e. IP address, not registered account)**
This installation is private, only for users who are sent access.
**2. Please clarify what "save your changes before publish" means.**
When a user is editing an article, you can save changes without publishing it.
This duplicate of records is given when the user saves the article.
In fact, I think that if an article has not been sent to be published, it should not appear in the list of revisions pending moderation.
![captura](https://user-images.githubusercontent.com/14800036/37367788-feb08898-26c9-11e8-86d0-a03df9309780.JPG)
**3. Does the problem go away if you set $wgSessionCacheType=CACHE_DB; in LocalSettings.php?**
I have added the variable, and they are also duplicated.
![captura](https://user-images.githubusercontent.com/14800036/37369127-d384c158-26cd-11e8-9a88-da8b8d29c349.JPG)

**Comment by edwardspec** [comment] 2018-03-13 21:49
> When a user is editing an article, you can save changes without publishing it.

Interesting. This feature (different buttons for Save/Publish) is not a part of MediaWiki itself (vanilla MediaWiki only has Save button, which always publishes).

Do you know what extension of MediaWiki adds this Publish button?
(if unknown, just tell me what extensions are installed, I'll determine which one)

**Comment by jocor87** [comment] 2018-03-13 21:59
Checking the LocalSettings.php, I see that the extension that the publish button adds is "WikiEditor"

![captura1](https://user-images.githubusercontent.com/14800036/37372123-4f8794ac-26d7-11e8-8b00-089180bd9434.JPG)

![captura](https://user-images.githubusercontent.com/14800036/37372128-56ef8b0a-26d7-11e8-8026-a8f2d585bc71.JPG)

**Comment by edwardspec** [comment] 2018-03-13 22:06
Investigating...

**Comment by jocor87** [comment] 2018-03-13 22:10
Thanks

**Comment by edwardspec** [comment] 2018-03-13 22:36
So far unable to reproduce. What I did:
1) I logged in as non-automoderated user "User 5".
2) I opened editing form of the page "Cat".
3) typed some words and clicked "Save page" (below the textarea field).
4) opened the editing form for the page "Cat" again.
5) typed more words, this time clicked "Publish".
6) logged in as moderator "User 1" and checked Special:Moderation. Only one row was shown (for "User 5" + "Cat").

Is this different from what the user was doing when the problem occured?

I also had a look at sources of "Publish" feature in Extension:WikiEditor, and "Publish" button seems to do exactly the same thing as "Save page" (it submits the same form) except for showing this extra popup ("please enter description of edit [...]").

**Comment by jocor87** [comment] 2018-03-13 22:55
1.  I logged in as non-automoderated user "testuser". This user have the next permissions:
![captura2](https://user-images.githubusercontent.com/14800036/37373987-bb506252-26de-11e8-9ca0-1231fea0f0c4.JPG)

2. I opened editing form of the page "Cat".
3. typed some words and clicked "Save page" (below the textarea field). I logged in as moderator and i see the next:
![captura](https://user-images.githubusercontent.com/14800036/37374030-de96f154-26de-11e8-98b8-9cc9391b8581.JPG)

4. opened the editing form for the page "Cat" again.
5. typed more words, this time clicked "Publish". Then logged in as moderator and i see the next:
![captura1](https://user-images.githubusercontent.com/14800036/37374070-0be0e836-26df-11e8-9d7e-f4cd38278b0b.JPG)
6. I give approved the first row, and then i see this:
![captura](https://user-images.githubusercontent.com/14800036/37374139-43338bc2-26df-11e8-86fc-52c630e0c818.JPG)

**Comment by edwardspec** [comment] 2018-03-13 22:59
Understood. So even one "Save page" can cause two rows.
I'm investigating several theories on what could have caused it.

**Comment by edwardspec** [comment] 2018-03-15 09:16
Please do the following test: in the file `util/RollbackResistantQuery.php`, replace the line
`protected function onRollback() { `
with:
`protected function onRollback() {  return;`

... and let me know if the issue disappeared.

**Comment by jocor87** [comment] 2018-03-15 21:18
Excellent, this work perfect. I can even save, then make more changes and press publish, and it remains as a single row.

**Comment by jocor87** [comment] 2018-03-15 21:25
Can i delete old entries from moderation table ?

**Comment by edwardspec** [comment] 2018-03-15 23:15
Should be fixed in Moderation v.1.1.19.
Please confirm that it works correctly (even without `$wgJobRunRate=0;` in LocalSettings.php).

> Can i delete old entries from moderation table ?

Manually, via the SQL query
`DELETE FROM moderation WHERE mod_rejected=1;`
As this is an irrevocable deletion of history, it's not safe to have a button for such actions in the web interface.

**Comment by edwardspec** [comment] 2018-03-25 18:13
@jocor87 Please confirm that duplicated records don't appear in the latest version of Moderation. (without `$wgJobRunRate=0;)`

**Comment by jocor87** [comment] 2018-03-26 10:57
Sorry for responding so far, in my LocalSettings.php file I do not have the variable $ wgJobRunRate = 0;

**Comment by edwardspec** [comment] 2018-03-26 11:07
Good, the problem is fixed then.
Thank you for your help.

**Closed by edwardspec** 2018-03-26 11:07 UTC
Labels: awaiting feedback from user(s), bug
