### ISSUE TITLE
Page Move (rename) is sill possible after adding the "Additional anti-vandalism tips" settings.

### ISSUE THREAD

**Issue by billpg** [edwardspec/mediawiki-moderation#46] opened 2019-05-23 20:20 UTC
I've installed the latest Moderation extension for MW 1.32.1 and I've saved the advised setting for restricting renames on the MediaWiki site.

$wgGroupPermissions['automoderated']['skip-move-moderation'] = false;
$wgGroupPermissions['sysop']['skip-move-moderation'] = true;

Despite my adding this (just after the wfLoadExtension for Moderation right at the end, I can still rename pages as my "normal" user.

**Comment by edwardspec** [comment] 2019-05-23 20:37
Investigating.

**Comment by edwardspec** [comment] 2019-05-23 21:10
Not reproduced.
Please check Special:ListGroupRights - it shows which groups have "skip-move-moderation" right.

**Comment by billpg** [comment] 2019-05-24 08:21
Please feel free to review at https://wiki.thesunsetlounge.co.uk/wiki/Special:ListGroupRights

Here's my local-settings. I added the last line to disable moves for all users until I can work this out. If you need me to remove that line, please let me know.

# Moderation - Keep this last.
wfLoadExtension( 'Moderation' );

# Require moderation for renames.
$wgGroupPermissions['automoderated']['skip-move-moderation'] = false;
$wgGroupPermissions['sysop']['skip-move-moderation'] = true;
$wgGroupPermissions['user']['move'] = false;

**Comment by edwardspec** [comment] 2019-05-24 09:11
Honestly, it looks like cache thing (you modified LocalSettings.php and immediately did the test, but the opcache of PHP still had the old version of LocalSettings).
Can you please retry the moving again?

Because the following line (which has nothing to do with Moderation) completely disables moves by users (there wouldn't even be a Move button), regardless of whether Moderation is installed or not:
```php
$wgGroupPermissions['user']['move'] = false;
`

**Comment by billpg** [comment] 2019-05-24 13:33
Just tried it again.

1. Commented out "move" line from local-settings.
2. Waited for normal user to see the Move button so I know cache has refreshed.
3. Created a new page as normal user.
4. WikiSysop approved page.
5. Normal user renames page. Rename is accepted without approval.

**Comment by edwardspec** [comment] 2019-05-24 17:55
I just remembered that another user faced a similar issue when update script (update.php) was invoked from the browser.
Running update.php from the command line fixed the issue for them.

I will investigate the underlying cause,
but in the mean time, can you try running update.php in the terminal?

**Comment by billpg** [comment] 2019-05-24 20:27
Alas, I'm on a commodity shared host and I don't think I can get shell access like that. I'm happy to just keep page moves as an admin-only function. I'll leave that line commented out for now in case you want me to try anything else.

**Comment by edwardspec** [comment] 2019-05-24 22:46
cPanel has a built-in Terminal in it (unless disabled on this particular hosting).

**Comment by edwardspec** [comment] 2019-05-30 00:06
Should be fixed in Moderation 1.3.31.
Please try it out (after running the web updater, page moves should now be intercepted) and confirm that it works for you.

**Comment by edwardspec** [comment] 2019-06-01 13:40
Closing as resolved.
Along with issue #44, which had the same cause.

**Closed by edwardspec** 2019-06-01 13:40 UTC
Labels: bug
